name: Trivy Scan and Generate SBOM

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      security-events: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master

      - name: Run Trivy Vulnerability Scan
        run: |
          trivy fs . \
            --severity HIGH,CRITICAL \
            --format table

      - name: Generate CycloneDX SBOM
        run: |
          trivy fs . \
            --format cyclonedx \
            --output sbom.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-report
          path: sbom.json

      - name: Upload SARIF Report
        run: |
          trivy fs . \
            --format sarif \
            --output trivy-results.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif
